spring:
  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true  # https://stackoverflow.com/a/67678945/548473
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20
  datasource:
    url: jdbc:h2:mem:voting
    username: sa
    password:
  h2.console.enabled: true
