spring:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20
  datasource:
    # ImMemory
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    # https://www.baeldung.com/spring-boot-hsqldb#2-the-applicationpropertiesfile
    url: jdbc:hsqldb:mem:voting;DB_CLOSE_DELAY=-1
    username: sa
    password: