db:
  path: mem:voting
  name: voting
  port: 9092

spring:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:{{db.path}};DB_CLOSE_DELAY=-1  # https://www.baeldung.com/spring-boot-hsqldb#2-the-applicationpropertiesfile
    username: sa
    password: